
name: ci

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 9.5

      - name: Install dependencies
        run: pnpm install
        
      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Lint
        run: pnpm lint

      - name: Run test suite
        run: pnpm test
